@startuml usecase
left to right direction
skinparam monochrome false
:Felhasználó: as U

U --> (Szimuláció futtatása)
U --> (Lefutott szimuláció betöltése)

(Robotok pozíciójának megadása) .-> (Szimuláció futtatása) : precedes
(Raktár alaprajzának megadása) .-> (Szimuláció futtatása) : precedes
(Útkereső algoritmus kiválasztása) .-> (Szimuláció futtatása) : precedes

(Szimuláció futtatása) .-> (Célpont kiválasztása) : extend
(Szimuláció futtatása) .-> (Naplófájl készítése) : invokes

(Szimuláció futtatása) .-> (Raktár megjelenítése) : invokes
(Lefutott szimuláció betöltése) .-> (Raktár megjelenítése) : invokes

(Lefutott szimuláció betöltése) .-> (Sebesség módosítása) : include
(Lefutott szimuláció betöltése) .-> (Lépegetés) : include
@enduml

@startuml sample
left to right direction
skinparam packageStyle rectangle
skinparam monochrome true
actor customer
actor clerk
rectangle checkout {
  customer -- (checkout)
  (checkout) .> (payment) : include
  (help) .> (checkout) : extends
  (checkout) -- clerk
}
@enduml