@startuml usecase
left to right direction
skinparam monochrome false
actor U as "Felhasználó"

rectangle Futtatás {
  U -- (Szimuláció futtatása)
  U -- (Robotok pozíciójának megadása)
  U -- (Raktár alaprajzának megadása)
  U -- (Útkereső algoritmus kiválasztása)
  U - (Célpont felülírása)

  (Robotok pozíciójának megadása) .-> (Szimuláció futtatása) : precedes
  (Raktár alaprajzának megadása) .-> (Szimuláció futtatása) : precedes
  (Útkereső algoritmus kiválasztása) .-> (Szimuláció futtatása) : precedes
  (Szimuláció futtatása) .-> (Célpont felülírása) : extend
  (Szimuláció futtatása) .-> (Naplófájl elkészülése) : invokes
}

rectangle Nézet {
  (Szimuláció futtatása) .-> (Raktár megjelenítése) : invokes
}

rectangle Visszajátszás {
  U -- (Lefutott szimuláció betöltése)

  (Lefutott szimuláció betöltése) .-> (Raktár megjelenítése) : invokes
  (Lefutott szimuláció betöltése) .-> (Sebesség módosítása) : include
  (Lefutott szimuláció betöltése) .-> (Lépegetés) : include
}
@enduml