### YamlMime:ManagedReference
items:
- uid: Mekkdonalds.Persistence.IConfigDataAccess
  commentId: T:Mekkdonalds.Persistence.IConfigDataAccess
  id: IConfigDataAccess
  parent: Mekkdonalds.Persistence
  children:
  - Mekkdonalds.Persistence.IConfigDataAccess.Load(System.String)
  langs:
  - csharp
  - vb
  name: IConfigDataAccess
  nameWithType: IConfigDataAccess
  fullName: Mekkdonalds.Persistence.IConfigDataAccess
  type: Interface
  source:
    remote:
      path: src/MekkdonaldsModel/Persistence/IConfigDataAccess.cs
      branch: feature/looks
      repo: git@szofttech.inf.elte.hu:szofttech-ab-2024/group-07/csapat3.git
    id: IConfigDataAccess
    path: ../src/MekkdonaldsModel/Persistence/IConfigDataAccess.cs
    startLine: 2
  assemblies:
  - MekkdonaldsModel
  namespace: Mekkdonalds.Persistence
  syntax:
    content: public interface IConfigDataAccess
    content.vb: Public Interface IConfigDataAccess
- uid: Mekkdonalds.Persistence.IConfigDataAccess.Load(System.String)
  commentId: M:Mekkdonalds.Persistence.IConfigDataAccess.Load(System.String)
  id: Load(System.String)
  parent: Mekkdonalds.Persistence.IConfigDataAccess
  langs:
  - csharp
  - vb
  name: Load(string)
  nameWithType: IConfigDataAccess.Load(string)
  fullName: Mekkdonalds.Persistence.IConfigDataAccess.Load(string)
  type: Method
  source:
    remote:
      path: src/MekkdonaldsModel/Persistence/IConfigDataAccess.cs
      branch: feature/looks
      repo: git@szofttech.inf.elte.hu:szofttech-ab-2024/group-07/csapat3.git
    id: Load
    path: ../src/MekkdonaldsModel/Persistence/IConfigDataAccess.cs
    startLine: 4
  assemblies:
  - MekkdonaldsModel
  namespace: Mekkdonalds.Persistence
  syntax:
    content: Task<Config> Load(string path)
    parameters:
    - id: path
      type: System.String
    return:
      type: System.Threading.Tasks.Task{Mekkdonalds.Persistence.Config}
    content.vb: Function Load(path As String) As Task(Of Config)
  overload: Mekkdonalds.Persistence.IConfigDataAccess.Load*
  nameWithType.vb: IConfigDataAccess.Load(String)
  fullName.vb: Mekkdonalds.Persistence.IConfigDataAccess.Load(String)
  name.vb: Load(String)
references:
- uid: Mekkdonalds.Persistence
  commentId: N:Mekkdonalds.Persistence
  href: Mekkdonalds.html
  name: Mekkdonalds.Persistence
  nameWithType: Mekkdonalds.Persistence
  fullName: Mekkdonalds.Persistence
  spec.csharp:
  - uid: Mekkdonalds
    name: Mekkdonalds
    href: Mekkdonalds.html
  - name: .
  - uid: Mekkdonalds.Persistence
    name: Persistence
    href: Mekkdonalds.Persistence.html
  spec.vb:
  - uid: Mekkdonalds
    name: Mekkdonalds
    href: Mekkdonalds.html
  - name: .
  - uid: Mekkdonalds.Persistence
    name: Persistence
    href: Mekkdonalds.Persistence.html
- uid: Mekkdonalds.Persistence.IConfigDataAccess.Load*
  commentId: Overload:Mekkdonalds.Persistence.IConfigDataAccess.Load
  href: Mekkdonalds.Persistence.IConfigDataAccess.html#Mekkdonalds_Persistence_IConfigDataAccess_Load_System_String_
  name: Load
  nameWithType: IConfigDataAccess.Load
  fullName: Mekkdonalds.Persistence.IConfigDataAccess.Load
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task{Mekkdonalds.Persistence.Config}
  commentId: T:System.Threading.Tasks.Task{Mekkdonalds.Persistence.Config}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<Config>
  nameWithType: Task<Config>
  fullName: System.Threading.Tasks.Task<Mekkdonalds.Persistence.Config>
  nameWithType.vb: Task(Of Config)
  fullName.vb: System.Threading.Tasks.Task(Of Mekkdonalds.Persistence.Config)
  name.vb: Task(Of Config)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: Mekkdonalds.Persistence.Config
    name: Config
    href: Mekkdonalds.Persistence.Config.html
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: Mekkdonalds.Persistence.Config
    name: Config
    href: Mekkdonalds.Persistence.Config.html
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
